pipeline {
 agent any

 stages {

  stage('Clone Repo') {
   steps {
    git 'https://github.com/akshat123456-ab/devops-end-to-end-project.git'
   }
  }

  stage('Build Docker Image') {
   steps {
    sh 'docker build -t devops-app ./app'
   }
  }

  stage('Run Container') {
   steps {
    sh 'docker run -d -p 3000:3000 devops-app'
   }
  }

 }

}
