pipeline {
 agent any

 environment {
  IMAGE_NAME = "devops-app"
  DOCKERHUB_USER = "akshat123mehra"
 }

 stages {

  stage('Terraform Init') {
   steps {
    sh 'cd terraform && terraform init'
   }
  }

  stage('Terraform Apply') {
   steps {
    sh 'cd terraform && terraform apply -auto-approve'
   }
  }

  stage('Build Docker Image') {
   steps {
    sh 'docker build -t $IMAGE_NAME ./app'
   }
  }

  stage('Tag Docker Image') {
   steps {
    sh 'docker tag $IMAGE_NAME $DOCKERHUB_USER/$IMAGE_NAME:latest'
   }
  }

  stage('Push Docker Image') {
   steps {
    sh 'docker push $DOCKERHUB_USER/$IMAGE_NAME:latest'
   }
  }

  stage('Run Ansible Playbook') {
   steps {
    sh 'ansible-playbook -i ansible/inventory ansible/playbook.yml'
   }
  }

 }
}
